title: "CT-Kompetenzzentrum Freiburg"
description: "Computed Tomography setups and results from various institutes and research groups in Freiburg."
author: "Inatech SSE"
theme: minimal-mistakes-jekyll

# URL Settings
url: "https://xrayalu.github.io"
baseurl: ""

# Navigation Structure
navigation:
  - title: "Pre-Clinical"
    children:
      - title: "Machine 1"
        url: /pre-clinical/machine-1
      - title: "Machine 2"
        url: /pre-clinical/machine-2
      - title: "Results"
        url: /pre-clinical/results
  - title: "Clinical"
    children:
      - title: "Machine A"
        url: /clinical/machine-a
      - title: "Machine B"
        url: /clinical/machine-b
      - title: "Results"
        url: /clinical/results
  - title: "Material Science"
    children:
      - title: "Machine X"
        url: /material-science/machine-x
      - title: "Machine Y"
        url: /material-science/machine-y
      - title: "Results"
        url: /material-science/results

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Markdown settings
markdown: kramdown

# Pagination (if you have blog posts or updates)
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules